'use strict';
const categories = {algebra:'Algebra',advanced:'Advanced Math',data:'Problem-Solving & Data Analysis',geometry:'Geometry & Trigonometry',ideas:'Information and Ideas',craft:'Craft and Structure',expression:'Expression of Ideas',conventions:'Standard English Conventions'};
const $ = id => document.getElementById(id);
let queue=[],index=0,answered=0,correct=0,streak=0,graded=false;
function available(){return QUESTIONS.filter(q=>($('subject').value==='all'||q.subject===$('subject').value)&&($('category').value==='all'||q.category===$('category').value)&&($('difficulty').value==='all'||q.difficulty===$('difficulty').value));}
function updateAvailability(){const n=available().length;$('availability').textContent=`${n} original questions available for this selection.`;$('start').disabled=n===0;}
function updateCategories(){const subject=$('subject').value;const previous=$('category').value;$('category').replaceChildren(new Option('All skills','all'));Object.entries(categories).forEach(([key,name])=>{if(QUESTIONS.some(q=>q.category===key&&(subject==='all'||q.subject===subject)))$('category').add(new Option(name,key));});if([...$('category').options].some(o=>o.value===previous))$('category').value=previous;updateAvailability();}
function stats(){$('answered').textContent=answered;$('accuracy').textContent=answered?Math.round(correct/answered*100)+'%':'—';$('streak').textContent=streak;}
function render(){graded=false;const q=queue[index];$('meta').textContent=`${q.subject==='math'?'Math':'Reading & Writing'} · ${categories[q.category]} · ${q.difficulty}`;$('position').textContent=`Question ${index+1} of ${queue.length}`;$('prompt').textContent=q.question;$('choices').replaceChildren();q.choices.forEach((choice,i)=>{const label=document.createElement('label');label.className='choice';const input=document.createElement('input');input.type='radio';input.name='answer';input.value=i;input.addEventListener('change',()=>{$('check').disabled=false;});const text=document.createElement('span');text.textContent=`${'ABCD'[i]}. ${choice}`;label.append(input,text);$('choices').append(label);});$('feedback').hidden=true;$('check').hidden=false;$('check').disabled=true;$('practice').hidden=false;}
function finish(){ $('practice').hidden=true;$('summary').hidden=false;$('summary-title').textContent=answered?'Good work. Keep building.':'Ready when you are.';$('summary-text').textContent=answered?`You answered ${correct} of ${answered} questions correctly (${Math.round(correct/answered*100)}%).\nPractice the explanations for any missed questions, then try another skill.`:'Choose a subject to begin a new session.';}
$('subject').addEventListener('change',updateCategories);$('category').addEventListener('change',updateAvailability);$('difficulty').addEventListener('change',updateAvailability);
$('start').addEventListener('click',()=>{queue=[...available()];for(let i=queue.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[queue[i],queue[j]]=[queue[j],queue[i]];}if(!queue.length)return;index=answered=correct=streak=0;stats();$('setup').hidden=true;$('summary').hidden=true;render();$('prompt').scrollIntoView({block:'center',behavior:'smooth'});});
$('check').addEventListener('click',()=>{const selection=document.querySelector('input[name="answer"]:checked');if(graded||!selection)return;graded=true;const q=queue[index],value=Number(selection.value),ok=value===q.answer;answered++;if(ok){correct++;streak++;}else streak=0;stats();[...$('choices').children].forEach((label,i)=>{label.querySelector('input').disabled=true;if(i===q.answer)label.classList.add('correct');else if(i===value)label.classList.add('wrong');});$('result').textContent=ok?'Correct!':`Correct answer: ${'ABCD'[q.answer]}`;$('explanation').textContent=q.explanation;$('check').hidden=true;$('feedback').hidden=false;$('next').textContent=index===queue.length-1?'View session summary →':'Next question →';$('feedback').focus();});
$('next').addEventListener('click',()=>{if(!graded)return;index++;if(index===queue.length)finish();else render();});$('end').addEventListener('click',finish);$('again').addEventListener('click',()=>{$('summary').hidden=true;$('setup').hidden=false;});updateCategories();
